language: node_js
node_js:
  - "8.12"
install:
  - npm install
script:
  - npm run generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: MonkeyBinBin/monkeybinbin.github.io
  target_branch: master
